# -*- coding: utf-8 -*-
"""BagofWordsModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZbSPU3EwUF2JBoXU2b1AKC9LLWwedVma
"""

!pip install nltk

paragraph="""Elon Reeve Musk (/ˈiːlɒn/; EE-lon; born June 28, 1971) is a businessman and investor. He is the founder, chairman, CEO, and CTO of SpaceX; angel investor, CEO, product architect, and former chairman of Tesla, Inc.; owner, chairman, and CTO of X Corp.; founder of the Boring Company and xAI; co-founder of Neuralink and OpenAI; and president of the Musk Foundation. He is the wealthiest person in the world, with an estimated net worth of US$232 billion as of December 2023, according to the Bloomberg Billionaires Index, and $254 billion according to Forbes, primarily from his ownership stakes in Tesla and SpaceX.[5][6]"""

paragraph

import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

## tokenization - converts paragraph-sentences-words
nltk.download("punkt")
sentences=nltk.sent_tokenize(paragraph)
print(sentences)

stemmer=PorterStemmer()
import re
corpus=[]
for i in range (len(sentences)):
  review=re.sub('[^A-Za-z]', ' ', sentences[i])
  review =review.lower()
  corpus.append(review)
  print(corpus)

corpus

## stemming
nltk.download('stopwords')
for i in corpus:
  words = nltk.word_tokenize(i)
  for word in words:
    if word not in set(stopwords.words('english')):
      print(stemmer.stem(word))

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(binary=True)
x=cv.fit_transform(corpus)
cv.vocabulary_

x[0].toarray()